name: test

# pull_request가 실행될때 해당 깃헙 액션이 발동됨
on: pull_request
jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      redis:
        image: redis
        ports:
          - 6380:6379
        options: --requirepass test_env
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install npm packages
        run: npm ci
      - name: Check Redis connection
        run: redis-cli -h localhost -p 6380 -a test_env ping
      - name: Run test
        run: npm run test:ci
        env:
          REDIS_URL: redis://default:test_env@localhost:6380
      - name: test build
        run: npm run build
